services:
  
  essays-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: essays-db
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"

  essays-db-migrations:
    depends_on:
      - essays-db
    container_name: essays-db-migrations
    build:
      context: .
      dockerfile: Core/src/Essays.Core.Migrations/Dockerfile
    environment:
      ConnectionStrings__EssaysContext: "Server=essays-db,1433;Database=EssaysDb;User Id=sa;Password=Test123!;TrustServerCertificate=True;"

  retriever-api:
    image: retriever-api
    depends_on:
      - essays-db
      - essays-db-migrations
    container_name: retriever-api
    build:
      context: .
      dockerfile: RetrieverApi/src/Essays.Retriever.Api/Dockerfile
    environment:
      ConnectionStrings__EssaysContext: "Server=essays-db,1433;Database=EssaysDb;User Id=sa;Password=Test123!;TrustServerCertificate=True;"
    ports:
      - "8080:8080"