services:
  
  essays-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: essays-db
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Test123!"
      ACCEPT_EULA: "Y"

  essays-db-migrations:
    depends_on:
      - essays-db
    container_name: essays-db-migrations
    build:
      context: .
      dockerfile: Core/src/Essays.Core.Migrator.Console/Dockerfile
    environment:
      ConnectionStrings__EssaysContext: "Server=essays-db,1433;Database=EssaysDb;User Id=sa;Password=Test123!;TrustServerCertificate=True;"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass Test123!"

  retriever-api:
    image: retriever-api
    depends_on:
      - essays-db
      - essays-db-migrations
      - redis
    container_name: retriever-api
    build:
      context: .
      dockerfile: RetrieverApi/src/Essays.Retriever.Api/Dockerfile
    environment:
      ConnectionStrings__EssaysContext: "Server=essays-db,1433;Database=EssaysDb;User Id=sa;Password=Test123!;TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis:6379,password=Test123!"
    ports:
      - "8080:8080"

  writer-api:
    image: writer-api
    depends_on:
      - essays-db
      - essays-db-migrations
      - redis
    container_name: writer-api
    build:
      context: .
      dockerfile: WriterApi/src/Essays.Writer.Api/Dockerfile
    environment:
      ConnectionStrings__EssaysContext: "Server=essays-db,1433;Database=EssaysDb;User Id=sa;Password=Test123!;TrustServerCertificate=True;"
      ConnectionStrings__Redis: "redis:6379,password=Test123!"
    ports:
      - "8081:8080"