
@WriterApi_HostAddress = http://localhost:8081
@Test_Essay_Id = ef519c4e-477d-4b51-a58b-e1adca84df47

GET {{WriterApi_HostAddress}}

###

POST {{WriterApi_HostAddress}}/essays/
Content-Type: application/json

{
    "Title": "Test Title 12",
    "Body": "This is a sample essay body for testing purposes. It contains more than one hundred characters to meet the minimum length requirement.",
    "Author": "Test Author 2"
}

###

PUT {{WriterApi_HostAddress}}/essays/{{Test_Essay_Id}}
Content-Type: application/json

{
  "Title": "Updated Test Title 12",
  "Body": "Updated Body - This is a sample essay body for testing purposes. It contains more than one hundred characters to meet the minimum length requirement.",
  "Author": "Updated - Test Author 2"
}

###

DELETE {{WriterApi_HostAddress}}/essays/{{Test_Essay_Id}}
