@RetrieverApi_HostAddress = http://localhost:8080
@Test_Essay_Id = 5db0c492-6d5c-4abb-971a-658a43e73bc9

GET {{RetrieverApi_HostAddress}}/

###

GET {{RetrieverApi_HostAddress}}/essays/{{Test_Essay_Id}}

###