@RetrieverApi_HostAddress = http://localhost:8080
@Test_Essay_Id = fc6372c0-d104-4dba-b9b8-57449140a9c2

GET {{RetrieverApi_HostAddress}}/

###

GET {{RetrieverApi_HostAddress}}/essays/{{Test_Essay_Id}}

###