@RetrieverApi_HostAddress = https://app-retriever-api-rv4qakzmk4hiy.azurewebsites.net/
@Test_Essay_Id = e1d32b81-f362-49e3-8062-39a0a5d3c881

GET {{RetrieverApi_HostAddress}}/

###

GET {{RetrieverApi_HostAddress}}/essays/{{Test_Essay_Id}}

###