name: Retriever Api

env:
  DOTNET_VERSION: 9.0.x
  BUILD_PATH: RetrieverApi/src/Essays.RetrieverApi/Essays.RetrieverApi.csproj
  ARTIFACT_PATH: artifacts

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: 
      - main
    paths:
      - RetrieverApi/**
  pull_request:
    branches:
      - main
    paths:
      - RetrieverApi/**
  workflow_dispatch: 

jobs:
  
  build:
    name: Build, test and publish Retriever Api
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch of repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: {{env.DOTNET_VERSION}}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Format
      run: dotnet format -v detailed --verify-no-changes
      
    - name: Publish
      run: dotnet publish ${{ env.BUILD_PATH }} -c Release -o ${{ env.ARTIFACT_PATH }}
      
    - name: Upload artifact for deployment job(s)
      uses: actions/upload-artifact@v4 
      with: 
        name: retriever-api
        path: ${{ env.ARTIFACT_PATH }}
        
  deploy-dev:
    name: Deploy Retriever Api to development environment
    runs-on: ubuntu-latest
    needs: build
    environment: Development
    
    steps:
      - name: Download artifact from previous build job
        uses: actions/download-artifact@v4
        with:
          name: retriever-api
          path: ${{ env.ARTIFACT_PATH }}
          
      - name: Login to Azure
        uses: azure/login@v2.1.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.RETRIEVAL_API_RESOURCE_NAME }}
          package: ${{ env.ARTIFACT_PATH }}